function [Veh] = Truck_2_3(Veh)
% Truck_2_3
% Created: 25-Jun-2019 17:10:03
 
% Copyright (c) 2019, Daniel Cantero. All rights reserved.
% Use, copy or distribution of this program is only allowed with the
% explicit authorization from the author. Please contact daniel.cantero@ntnu.no
 
% -- Vehicle information --
% num_axles_per_body = [2  3];
% num_axles_per_group = [1  1  1  1  1];
% with_articulation = [1];
 
% -- Vehicle variables --
% Veh.Prop.mBi = [[mB1, mB2]]
% Veh.Prop.IyBi = [[IyB1, IyB2]]
% Veh.Prop.kTi = [[kT1, kT2, kT3, kT4, kT5]]
% Veh.Prop.cTi = [[cT1, cT2, cT3, cT4, cT5]]
% Veh.Prop.kSi = [[kS1, kS2, kS3, kS4, kS5]]
% Veh.Prop.cSi = [[cS1, cS2, cS3, cS4, cS5]]
% Veh.Prop.mSi = [[mS1, mS2, mS3, mS4, mS5]]
% Veh.Prop.afBi = [[afB1, afB2]]
% Veh.Prop.abBi = [abB1]
% Veh.Prop.ei = [[e1, e2, e3, e4, e5]]
 
% -- Degrees of Freedom --
Veh.DOF(1).name = 'yB1'; Veh.DOF(1).type = 'displacement'; Veh.DOF(1).dependency = 'independent';
Veh.DOF(2).name = 'thetaB1'; Veh.DOF(2).type = 'rotation'; Veh.DOF(2).dependency = 'independent';
Veh.DOF(3).name = 'thetaB2'; Veh.DOF(3).type = 'rotation'; Veh.DOF(3).dependency = 'independent';
Veh.DOF(4).name = 'yS1'; Veh.DOF(4).type = 'displacement'; Veh.DOF(4).dependency = 'independent';
Veh.DOF(5).name = 'yS2'; Veh.DOF(5).type = 'displacement'; Veh.DOF(5).dependency = 'independent';
Veh.DOF(6).name = 'yS3'; Veh.DOF(6).type = 'displacement'; Veh.DOF(6).dependency = 'independent';
Veh.DOF(7).name = 'yS4'; Veh.DOF(7).type = 'displacement'; Veh.DOF(7).dependency = 'independent';
Veh.DOF(8).name = 'yS5'; Veh.DOF(8).type = 'displacement'; Veh.DOF(8).dependency = 'independent';
Veh.DOF(1).num_independent = 8;
 
% -- DOF relations -- 
Veh.DOF(9).name = 'yB2'; Veh.DOF(9).type = 'displacement'; Veh.DOF(9).dependency = 'dependent';
Veh.DOF(9).expression = 'yB2 = yB1 + abB1*thetaB1 + afB2*thetaB2';
Veh.DOF(9).fun = @(y) y(1) + Veh.Prop.abBi(1)*y(2) + Veh.Prop.afBi(2)*y(3);
Veh.DOF(1).num_dependent = 1;
 
% -- Axle spacing and distance --
Veh.Prop.ax_sp = [0, Veh.Prop.ei(2) - Veh.Prop.ei(1), Veh.Prop.abBi(1) + Veh.Prop.afBi(2) - Veh.Prop.ei(2) + Veh.Prop.ei(3), Veh.Prop.ei(4) - Veh.Prop.ei(3), Veh.Prop.ei(5) - Veh.Prop.ei(4)];
Veh.Prop.ax_dist = [0, Veh.Prop.ei(2) - Veh.Prop.ei(1), Veh.Prop.abBi(1) + Veh.Prop.afBi(2) - Veh.Prop.ei(1) + Veh.Prop.ei(3), Veh.Prop.abBi(1) + Veh.Prop.afBi(2) - Veh.Prop.ei(1) + Veh.Prop.ei(4), Veh.Prop.abBi(1) + Veh.Prop.afBi(2) - Veh.Prop.ei(1) + Veh.Prop.ei(5)];
 
% -- Vehicle system matrices --
Veh.SysM.M = ...
[[Veh.Prop.mBi(1) + Veh.Prop.mBi(2), Veh.Prop.abBi(1)*Veh.Prop.mBi(2), Veh.Prop.afBi(2)*Veh.Prop.mBi(2), 0, 0, 0, 0, 0]; ...
[Veh.Prop.abBi(1)*Veh.Prop.mBi(2), Veh.Prop.IyBi(1) + Veh.Prop.abBi(1)^2*Veh.Prop.mBi(2), Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.mBi(2), 0, 0, 0, 0, 0]; ...
[Veh.Prop.afBi(2)*Veh.Prop.mBi(2), Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.mBi(2), Veh.Prop.IyBi(2) + Veh.Prop.afBi(2)^2*Veh.Prop.mBi(2), 0, 0, 0, 0, 0]; ...
[0, 0, 0, Veh.Prop.mSi(1), 0, 0, 0, 0]; ...
[0, 0, 0, 0, Veh.Prop.mSi(2), 0, 0, 0]; ...
[0, 0, 0, 0, 0, Veh.Prop.mSi(3), 0, 0]; ...
[0, 0, 0, 0, 0, 0, Veh.Prop.mSi(4), 0]; ...
[0, 0, 0, 0, 0, 0, 0, Veh.Prop.mSi(5)]];
 
Veh.SysM.C = ...
[[Veh.Prop.cSi(1) + Veh.Prop.cSi(2) + Veh.Prop.cSi(3) + Veh.Prop.cSi(4) + Veh.Prop.cSi(5), Veh.Prop.abBi(1)*Veh.Prop.cSi(3) + Veh.Prop.abBi(1)*Veh.Prop.cSi(4) + Veh.Prop.abBi(1)*Veh.Prop.cSi(5) + Veh.Prop.cSi(1)*Veh.Prop.ei(1) + Veh.Prop.cSi(2)*Veh.Prop.ei(2), Veh.Prop.afBi(2)*Veh.Prop.cSi(3) + Veh.Prop.afBi(2)*Veh.Prop.cSi(4) + Veh.Prop.afBi(2)*Veh.Prop.cSi(5) + Veh.Prop.cSi(3)*Veh.Prop.ei(3) + Veh.Prop.cSi(4)*Veh.Prop.ei(4) + Veh.Prop.cSi(5)*Veh.Prop.ei(5), -Veh.Prop.cSi(1), -Veh.Prop.cSi(2), -Veh.Prop.cSi(3), -Veh.Prop.cSi(4), -Veh.Prop.cSi(5)]; ...
[Veh.Prop.abBi(1)*Veh.Prop.cSi(3) + Veh.Prop.abBi(1)*Veh.Prop.cSi(4) + Veh.Prop.abBi(1)*Veh.Prop.cSi(5) + Veh.Prop.cSi(1)*Veh.Prop.ei(1) + Veh.Prop.cSi(2)*Veh.Prop.ei(2), Veh.Prop.abBi(1)^2*Veh.Prop.cSi(3) + Veh.Prop.abBi(1)^2*Veh.Prop.cSi(4) + Veh.Prop.abBi(1)^2*Veh.Prop.cSi(5) + Veh.Prop.cSi(1)*Veh.Prop.ei(1)^2 + Veh.Prop.cSi(2)*Veh.Prop.ei(2)^2, Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.cSi(3) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.cSi(4) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.cSi(5) + Veh.Prop.abBi(1)*Veh.Prop.cSi(3)*Veh.Prop.ei(3) + Veh.Prop.abBi(1)*Veh.Prop.cSi(4)*Veh.Prop.ei(4) + Veh.Prop.abBi(1)*Veh.Prop.cSi(5)*Veh.Prop.ei(5), -Veh.Prop.cSi(1)*Veh.Prop.ei(1), -Veh.Prop.cSi(2)*Veh.Prop.ei(2), -Veh.Prop.abBi(1)*Veh.Prop.cSi(3), -Veh.Prop.abBi(1)*Veh.Prop.cSi(4), -Veh.Prop.abBi(1)*Veh.Prop.cSi(5)]; ...
[Veh.Prop.afBi(2)*Veh.Prop.cSi(3) + Veh.Prop.afBi(2)*Veh.Prop.cSi(4) + Veh.Prop.afBi(2)*Veh.Prop.cSi(5) + Veh.Prop.cSi(3)*Veh.Prop.ei(3) + Veh.Prop.cSi(4)*Veh.Prop.ei(4) + Veh.Prop.cSi(5)*Veh.Prop.ei(5), Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.cSi(3) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.cSi(4) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.cSi(5) + Veh.Prop.abBi(1)*Veh.Prop.cSi(3)*Veh.Prop.ei(3) + Veh.Prop.abBi(1)*Veh.Prop.cSi(4)*Veh.Prop.ei(4) + Veh.Prop.abBi(1)*Veh.Prop.cSi(5)*Veh.Prop.ei(5), Veh.Prop.afBi(2)^2*Veh.Prop.cSi(3) + Veh.Prop.afBi(2)^2*Veh.Prop.cSi(4) + Veh.Prop.afBi(2)^2*Veh.Prop.cSi(5) + Veh.Prop.cSi(3)*Veh.Prop.ei(3)^2 + Veh.Prop.cSi(4)*Veh.Prop.ei(4)^2 + Veh.Prop.cSi(5)*Veh.Prop.ei(5)^2 + 2*Veh.Prop.afBi(2)*Veh.Prop.cSi(3)*Veh.Prop.ei(3) + 2*Veh.Prop.afBi(2)*Veh.Prop.cSi(4)*Veh.Prop.ei(4) + 2*Veh.Prop.afBi(2)*Veh.Prop.cSi(5)*Veh.Prop.ei(5), 0, 0, - Veh.Prop.afBi(2)*Veh.Prop.cSi(3) - Veh.Prop.cSi(3)*Veh.Prop.ei(3), - Veh.Prop.afBi(2)*Veh.Prop.cSi(4) - Veh.Prop.cSi(4)*Veh.Prop.ei(4), - Veh.Prop.afBi(2)*Veh.Prop.cSi(5) - Veh.Prop.cSi(5)*Veh.Prop.ei(5)]; ...
[-Veh.Prop.cSi(1), -Veh.Prop.cSi(1)*Veh.Prop.ei(1), 0, Veh.Prop.cSi(1) + Veh.Prop.cTi(1), 0, 0, 0, 0]; ...
[-Veh.Prop.cSi(2), -Veh.Prop.cSi(2)*Veh.Prop.ei(2), 0, 0, Veh.Prop.cSi(2) + Veh.Prop.cTi(2), 0, 0, 0]; ...
[-Veh.Prop.cSi(3), -Veh.Prop.abBi(1)*Veh.Prop.cSi(3), - Veh.Prop.afBi(2)*Veh.Prop.cSi(3) - Veh.Prop.cSi(3)*Veh.Prop.ei(3), 0, 0, Veh.Prop.cSi(3) + Veh.Prop.cTi(3), 0, 0]; ...
[-Veh.Prop.cSi(4), -Veh.Prop.abBi(1)*Veh.Prop.cSi(4), - Veh.Prop.afBi(2)*Veh.Prop.cSi(4) - Veh.Prop.cSi(4)*Veh.Prop.ei(4), 0, 0, 0, Veh.Prop.cSi(4) + Veh.Prop.cTi(4), 0]; ...
[-Veh.Prop.cSi(5), -Veh.Prop.abBi(1)*Veh.Prop.cSi(5), - Veh.Prop.afBi(2)*Veh.Prop.cSi(5) - Veh.Prop.cSi(5)*Veh.Prop.ei(5), 0, 0, 0, 0, Veh.Prop.cSi(5) + Veh.Prop.cTi(5)]];
 
Veh.SysM.K = ...
[[Veh.Prop.kSi(1) + Veh.Prop.kSi(2) + Veh.Prop.kSi(3) + Veh.Prop.kSi(4) + Veh.Prop.kSi(5), Veh.Prop.abBi(1)*Veh.Prop.kSi(3) + Veh.Prop.abBi(1)*Veh.Prop.kSi(4) + Veh.Prop.abBi(1)*Veh.Prop.kSi(5) + Veh.Prop.ei(1)*Veh.Prop.kSi(1) + Veh.Prop.ei(2)*Veh.Prop.kSi(2), Veh.Prop.afBi(2)*Veh.Prop.kSi(3) + Veh.Prop.afBi(2)*Veh.Prop.kSi(4) + Veh.Prop.afBi(2)*Veh.Prop.kSi(5) + Veh.Prop.ei(3)*Veh.Prop.kSi(3) + Veh.Prop.ei(4)*Veh.Prop.kSi(4) + Veh.Prop.ei(5)*Veh.Prop.kSi(5), -Veh.Prop.kSi(1), -Veh.Prop.kSi(2), -Veh.Prop.kSi(3), -Veh.Prop.kSi(4), -Veh.Prop.kSi(5)]; ...
[Veh.Prop.abBi(1)*Veh.Prop.kSi(3) + Veh.Prop.abBi(1)*Veh.Prop.kSi(4) + Veh.Prop.abBi(1)*Veh.Prop.kSi(5) + Veh.Prop.ei(1)*Veh.Prop.kSi(1) + Veh.Prop.ei(2)*Veh.Prop.kSi(2), Veh.Prop.abBi(1)^2*Veh.Prop.kSi(3) + Veh.Prop.abBi(1)^2*Veh.Prop.kSi(4) + Veh.Prop.abBi(1)^2*Veh.Prop.kSi(5) + Veh.Prop.ei(1)^2*Veh.Prop.kSi(1) + Veh.Prop.ei(2)^2*Veh.Prop.kSi(2), Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.kSi(3) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.kSi(4) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.kSi(5) + Veh.Prop.abBi(1)*Veh.Prop.ei(3)*Veh.Prop.kSi(3) + Veh.Prop.abBi(1)*Veh.Prop.ei(4)*Veh.Prop.kSi(4) + Veh.Prop.abBi(1)*Veh.Prop.ei(5)*Veh.Prop.kSi(5), -Veh.Prop.ei(1)*Veh.Prop.kSi(1), -Veh.Prop.ei(2)*Veh.Prop.kSi(2), -Veh.Prop.abBi(1)*Veh.Prop.kSi(3), -Veh.Prop.abBi(1)*Veh.Prop.kSi(4), -Veh.Prop.abBi(1)*Veh.Prop.kSi(5)]; ...
[Veh.Prop.afBi(2)*Veh.Prop.kSi(3) + Veh.Prop.afBi(2)*Veh.Prop.kSi(4) + Veh.Prop.afBi(2)*Veh.Prop.kSi(5) + Veh.Prop.ei(3)*Veh.Prop.kSi(3) + Veh.Prop.ei(4)*Veh.Prop.kSi(4) + Veh.Prop.ei(5)*Veh.Prop.kSi(5), Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.kSi(3) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.kSi(4) + Veh.Prop.abBi(1)*Veh.Prop.afBi(2)*Veh.Prop.kSi(5) + Veh.Prop.abBi(1)*Veh.Prop.ei(3)*Veh.Prop.kSi(3) + Veh.Prop.abBi(1)*Veh.Prop.ei(4)*Veh.Prop.kSi(4) + Veh.Prop.abBi(1)*Veh.Prop.ei(5)*Veh.Prop.kSi(5), Veh.Prop.afBi(2)^2*Veh.Prop.kSi(3) + Veh.Prop.afBi(2)^2*Veh.Prop.kSi(4) + Veh.Prop.afBi(2)^2*Veh.Prop.kSi(5) + Veh.Prop.ei(3)^2*Veh.Prop.kSi(3) + Veh.Prop.ei(4)^2*Veh.Prop.kSi(4) + Veh.Prop.ei(5)^2*Veh.Prop.kSi(5) + 2*Veh.Prop.afBi(2)*Veh.Prop.ei(3)*Veh.Prop.kSi(3) + 2*Veh.Prop.afBi(2)*Veh.Prop.ei(4)*Veh.Prop.kSi(4) + 2*Veh.Prop.afBi(2)*Veh.Prop.ei(5)*Veh.Prop.kSi(5), 0, 0, - Veh.Prop.afBi(2)*Veh.Prop.kSi(3) - Veh.Prop.ei(3)*Veh.Prop.kSi(3), - Veh.Prop.afBi(2)*Veh.Prop.kSi(4) - Veh.Prop.ei(4)*Veh.Prop.kSi(4), - Veh.Prop.afBi(2)*Veh.Prop.kSi(5) - Veh.Prop.ei(5)*Veh.Prop.kSi(5)]; ...
[-Veh.Prop.kSi(1), -Veh.Prop.ei(1)*Veh.Prop.kSi(1), 0, Veh.Prop.kSi(1) + Veh.Prop.kTi(1), 0, 0, 0, 0]; ...
[-Veh.Prop.kSi(2), -Veh.Prop.ei(2)*Veh.Prop.kSi(2), 0, 0, Veh.Prop.kSi(2) + Veh.Prop.kTi(2), 0, 0, 0]; ...
[-Veh.Prop.kSi(3), -Veh.Prop.abBi(1)*Veh.Prop.kSi(3), - Veh.Prop.afBi(2)*Veh.Prop.kSi(3) - Veh.Prop.ei(3)*Veh.Prop.kSi(3), 0, 0, Veh.Prop.kSi(3) + Veh.Prop.kTi(3), 0, 0]; ...
[-Veh.Prop.kSi(4), -Veh.Prop.abBi(1)*Veh.Prop.kSi(4), - Veh.Prop.afBi(2)*Veh.Prop.kSi(4) - Veh.Prop.ei(4)*Veh.Prop.kSi(4), 0, 0, 0, Veh.Prop.kSi(4) + Veh.Prop.kTi(4), 0]; ...
[-Veh.Prop.kSi(5), -Veh.Prop.abBi(1)*Veh.Prop.kSi(5), - Veh.Prop.afBi(2)*Veh.Prop.kSi(5) - Veh.Prop.ei(5)*Veh.Prop.kSi(5), 0, 0, 0, 0, Veh.Prop.kSi(5) + Veh.Prop.kTi(5)]];
 
% -- Force vector to calculate static response --
% Note: When using this vector, multiply it by the gravity. Following the sign criteria defined here
%   gravity has negative value. The numerical value to use is grav = -9.81 m/s^2
Veh.Static.F_vector_no_grav = [Veh.Prop.mBi(1) + Veh.Prop.mBi(2), Veh.Prop.abBi(1)*Veh.Prop.mBi(2), Veh.Prop.afBi(2)*Veh.Prop.mBi(2), Veh.Prop.mSi(1), Veh.Prop.mSi(2), Veh.Prop.mSi(3), Veh.Prop.mSi(4), Veh.Prop.mSi(5)];
 
% -- Nodal disp. to wheel disp. relation --
Veh.SysM.N2w = ...
[[0, 0, 0, 1, 0, 0, 0, 0]; ...
[0, 0, 0, 0, 1, 0, 0, 0]; ...
[0, 0, 0, 0, 0, 1, 0, 0]; ...
[0, 0, 0, 0, 0, 0, 1, 0]; ...
[0, 0, 0, 0, 0, 0, 0, 1]];
 
% ---- End of function ----